DEMO_CASES = [
    {
        "id": "hangzhou-weekend",
        "title": "南京出发杭州 3 日周末游",
        "origin_city": "南京",
        "destination_city": "杭州",
        "departure_date": "2026-05-01",
        "return_date": "2026-05-03",
        "budget_cny": 2800,
        "preference_mode": "balanced",
        "allow_night_arrival": False,
        "min_transfer_buffer_minutes": 60,
        "travelers": 2,
        "preferences": ["citywalk", "local_food", "light_pace"],
    },
    {
        "id": "xiamen-family",
        "title": "广州出发厦门 4 日亲子游",
        "origin_city": "广州",
        "destination_city": "厦门",
        "departure_date": "2026-06-11",
        "return_date": "2026-06-14",
        "budget_cny": 5200,
        "preference_mode": "peace_of_mind",
        "allow_night_arrival": False,
        "min_transfer_buffer_minutes": 90,
        "travelers": 3,
        "preferences": ["family_friendly", "beach", "seafood"],
    },
    {
        "id": "chengdu-foodie",
        "title": "上海出发成都 5 日美食慢游",
        "origin_city": "上海",
        "destination_city": "成都",
        "departure_date": "2026-09-16",
        "return_date": "2026-09-20",
        "budget_cny": 4600,
        "preference_mode": "budget_first",
        "allow_night_arrival": True,
        "min_transfer_buffer_minutes": 45,
        "travelers": 2,
        "preferences": ["local_food", "museum", "slow_travel"],
    },
]
